language: node_js
node_js:
  - "6"

branches:
  only:
  - master

before_install:
  - npm install -g yarn

install: make install
script: make coverage

after_script: make report

notifications:
  email:
    on_success: change
    on_failure: change
