- hosts: all
  become: yes
  vars:
    nodejs_version: 6.x
  roles:
    - role: angstwad.docker_ubuntu
      docker_group_members: [ vagrant ]
  tasks:
    - name: nodesource apt key installed
      apt_key:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
        id: "68576280"
        state: present

    - name: nodesource nodejs repo installed
      apt_repository:
        repo: "{{ item }}"
        state: present
      with_items:
        - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
        - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"

    - name: apps installed
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      with_items:
        - git
        - nodejs
